# docker-compose.prod.yml (本番用オーバーライドファイル)
# docker-compose.yml に対する本番環境用の差分を定義します。

services:
  remix:
    container_name: remix
    restart: unless-stopped
    networks:
      - external_network # Caddy用の外部ネットワークを追加
    labels:
      caddy: your_domain.com
      caddy.reverse_proxy: "{{.Name}}:3000"

  api:
    container_name: api
    restart: unless-stopped

  orm:
    container_name: orm
    command: sh -c "npx prisma migrate deploy && npx prisma generate"

  postgres:
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  external_network:
    external: true
    name: your_external_network # Caddyなどが属する既存のネットワーク名

volumes:
  postgres_data: