services:
  # Frontend Service (Remix)
  remix:
    build:
      context: ./remix
      target: prod
      args:
        API_BASE_URL: ${API_BASE_URL}
        WS_URL: ${WS_URL}
    container_name: remix_app_prod
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
      schema-generator: # Remixはスキーマ生成に依存
        condition: service_completed_successfully # schema-generatorが成功裏に完了するまで待つ
    networks:
      - app_network
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - WS_URL=${WS_URL}
    volumes:
      # ローカルパッケージをマウント
      - ./database_schema/client-sdk:/app/database_schema/client-sdk

  # Backend API Service (NestJS)
  api:
    build:
      context: ./api
      target: prod
    container_name: api_server_prod
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      schema-generator:
        condition: service_completed_successfully
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./database_schema/client-sdk:/app/database_schema/client-sdk # ローカルパッケージをマウント

  # 新しいサービス: Prismaスキーマ生成 & SDKビルド (本番ビルド用)
  schema-generator:
    build:
      context: ./database_schema
      target: prod # Dockerfileのprodターゲットを使用 (もしあれば)
    container_name: prisma_schema_prod
    volumes:
      - ./database_schema:/app # database_schemaディレクトリ全体をマウント
    working_dir: /app
    command: >
      sh -c "yarn install --pure-lockfile && yarn migrate:deploy && yarn generate && yarn build-sdk"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy # データベースの準備ができてからマイグレーション

  # Database Service (PostgreSQL)
  postgres:
    image: postgres:17-alpine
    container_name: database_prod
    # .envファイルから直接読み込む
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: